### ISSUE TITLE
Cartographer sensor not receiving data or Communication timeout during homing probe

### ISSUE THREAD

**Issue by devolf92** [Cartographer3D/cartographer-klipper#14]
Receiving this error after bed mesh calibrating or sometimes random even while sensor is not in use. Cant google anythig about this error.
Firmware is stock CAN, connected to ebb sb2209 can.
Klipper is uptodate

sometimes i got Communication timeout during homing probe while QGL on my voron 2.4
looks like things getting worse wen enclosure get hotter

![image](https://github.com/Cartographer3D/cartographer-klipper/assets/15054594/d03d3763-e2c2-4743-9d25-2547a8bfd19a)

**Comment by cruiten** [comment]
I recommend that you open a support issue on the Cartographer Discord Help and Support channel: https://discord.gg/HBmJnk4y
(This link will only be good for seven days)

You can also check out this excellent guide: https://canbus.esoterical.online/troubleshooting/timeout_during_homing_probing.html

**Comment by devolf92** [comment]
Thanks for your reply
I'm currently using fix with TRSYNC_TIMEOUT since this issue started. But this dirty status driving me mad.
Looks like this is fresh new guide or i miss it, thanks!
