### ISSUE TITLE
Klipper update broke "probe" name registration

### ISSUE THREAD

**Issue by HoCoK31** [Cartographer3D/cartographer-klipper#140]
Recent main branch klipper commit broke "probe" command registration from cartographer.

https://github.com/Klipper3d/klipper/commit/5493c603735d52ff1c03c0fa82a405edc30bd14c

**Comment by HoCoK31** [comment]
Error triggered by this line:

https://github.com/Cartographer3D/cartographer-klipper/blob/8324877a6dbe9bc9b4f4c2f2f5541349c55712fe/cartographer.py#L148

**Comment by krautech** [comment]
Thanks for making us aware of this, this will continue to happen while kevin does work on the probing/homing modules.

Its not an issue with scanner and new firmware so please update.

https://github.com/Cartographer3D/cartographer-klipper/issues/140

**Comment by marekdovjak** [comment]
@krautech Got the same error, so I followed the cartographer to scanner guide, now got this error

![image](https://github.com/user-attachments/assets/697cab01-e046-4dde-a881-a8a783e87bfa)

I have to comment the "lis2dw" and "resonance_tester" in printer.cfg to make it work again. What's the issue with the lis2dw?

[printer.cfg.zip](https://github.com/user-attachments/files/18022401/printer.cfg.zip)

**Comment by krautech** [comment]
Yeah klipper pushed updates that broke lis2dw communication.

There is a fix in beta atm, couple more days it will go to release for everyone

@marekdovjak
