### ISSUE TITLE
Support danger klipper is_non_critical

### ISSUE THREAD

**Issue by pellcorp** [Cartographer3D/cartographer-klipper#141]
It is possible to set is_non_critical flag on `[scanner]` config to prevent klipper stopping if the cartographer disconnects, but even though danger klipper does allow the cartographer to reconnect, klipper will crash when you try to next home Z.   So the scanner.py needs to properly support reconnect mode of danger klipper.

**Comment by krautech** [comment]
https://github.com/Cartographer3D/cartographer-klipper/blob/master/scanner.py#L479

Is where it crashes which is handled by the klipper side of things
I had it successfully reconnect and displaying data however when it would call this function from klippy it would force klipper restart without an error log or error message.

Maybe someone else could investigate. I had it down to it being a klippy side issue rather than scanner.

**Comment by pellcorp** [comment]
So when trying to home Z on the printer after the cartographer reconnects we actually get a proper crash with a page fault

![image](https://github.com/user-attachments/assets/1b1860bb-bb6d-4fdc-b408-0da3c8c357a0)

**Comment by krautech** [comment]
> So when trying to home Z on the printer after the cartographer reconnects we actually get a proper crash with a page fault
> 
> ![image](https://private-user-images.githubusercontent.com/274990/393007641-1b1860bb-bb6d-4fdc-b408-0da3c8c357a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTY0OTksIm5iZiI6MTczMzQ5NjE5OSwicGF0aCI6Ii8yNzQ5OTAvMzkzMDA3NjQxLTFiMTg2MGJiLWJiNmQtNGZkYy1iNDA4LTBkYTNjOGMzNTdhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNDQzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTYxZWM5YTlmMjI4M2JjYWNkYWQ5ODE0NjAwOGZhNDg4NjJkMmFjMDMyNGZjYzFhZDkxMjk0MzZjZjQ1ZGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yreON3QTlWF6XE9zXRxq1NpWFphnao1U0_tA_EHTwI0)

interesting, I dont know what we can do with this information however, looks like a kernel issue? I'll do some digging

**Comment by krautech** [comment]
what FW and Cartographer-Klipper code is this with?

**Comment by pellcorp** [comment]
I'm closing this issue, its no longer relevant for Simple AF
