### ISSUE TITLE
The K1 specific beta firmware does not report the right version

### ISSUE THREAD

**Issue by pellcorp** [Cartographer3D/cartographer-klipper#148]
I did properly flash :

/home/jason-pell/Development/cartographer-klipper/firmware/v2-v3/survey/5.1.0/Survey_Cartographer_K1_USB_8kib_offset.bin

And get this

![image](https://github.com/user-attachments/assets/12299fd3-7c7f-4335-a969-1f362f858f4d)

**Comment by krautech** [comment]
#159 should be merged into master now
