### ISSUE TITLE
Speed of Z homing and QGL slow despite speeds being set to 300 mm/s

### ISSUE THREAD

**Issue by cray12399** [Cartographer3D/cartographer-klipper#15]
Hi, I recently installed the cartographer probe on my printer. Everything is working perfectly. However, the speed at which my toolhead centers itself to home Z and the speed at which it moves to the QGL points are extremely slow after installing this probe. My QGL speed is set to 500 mm/s and Z homing is set to 300 mm/s, yet it is still moving incredibly slowly.

Is there some way to change this with the cartographer probe?

**Comment by cruiten** [comment]
I recommend that you open a support issue on the Cartographer Discord Help and Support channel: https://discord.gg/HBmJnk4y
(This link will only be good for seven days)
