### ISSUE TITLE
Klipper error after update

### ISSUE THREAD

**Issue by ModularPrintingSystem** [Cartographer3D/cartographer-klipper#168]
Since I updated klipper I get following error:
![Screenshot 2024-12-08 113520](https://github.com/user-attachments/assets/cb5e8d9a-9ccf-4cfa-bc62-0313552c3b7b)

**Comment by krautech** [comment]
Did you check troubleshooting at all? 🤔

https://docs.cartographer3d.com/cartographer-probe/troubleshooting

**Comment by ModularPrintingSystem** [comment]
Thank you, I didn't look at it, but after following the troubleshootinh guide I got another error, that I couldn't fin
![Screenshot 2024-12-08 122258](https://github.com/user-attachments/assets/d7dc9a7e-9a63-49d9-ad29-89735995e8af)
d

**Comment by krautech** [comment]
Lis2dw probes are currently broken thanks to klipper.

You need to comment out the [lis2dw] section

This is fixed in 1.1.0 which will be released in the next 24-ish hours.

**Comment by ModularPrintingSystem** [comment]
Okay, thank you
