### ISSUE TITLE
Missing Katapult_CAN_500000.bin

### ISSUE THREAD

**Issue by radekdoulik** [Cartographer3D/cartographer-klipper#19]
I am looking for katapult CAN 500k version of the bootloader, which is currently missing.

Could you please add it or share the menuconfig settings? I have the IDM probe, which has 24Mhz crystal, STM32 F042G6. What are the other option values?

BTW, I guess for IDM I will need the v2 firmware when I am switching to cartographer firmware, is that right?

**Comment by krautech** [comment]
Is this still a concern? All relevant firmwares have now been added. v2 and v3 firmwares are now combined.
