### ISSUE TITLE
Cartographer probe show  wrong Temp with minus value

### ISSUE THREAD

**Issue by Sprocyon** [Cartographer3D/cartographer-klipper#20]
Hi, my cartographer shows strange values from minus 59 to minus 74 degrees all the time, can you tell me what I can do about it?
![Uploading Cartographer.png…]()

**Comment by cruiten** [comment]
I recommend that you open a support issue on the Cartographer Discord Help and Support channel: https://discord.gg/HBmJnk4y
(This link will only be good for seven days)
