### ISSUE TITLE
Option 'calibration_method' in section 'scanner' is deprecated.

### ISSUE THREAD

**Issue by ChrisH2403** [Cartographer3D/cartographer-klipper#203]
Klipper gives me this warning after updating to the latest Version of Cartographer v1.1.0-0-gd23a793f aswell as Firmware 5.1.0.0.

In the [scanner] config my calibration_method is set to touch.

**Comment by krautech** [comment]
Check announcements on discord.

GitHub issues are for code related errors etc.
