### ISSUE TITLE
"No cartographer model loaded" error after update to v47

### ISSUE THREAD

**Issue by rovoe** [Cartographer3D/cartographer-klipper#28]
![image](https://github.com/user-attachments/assets/1c1c698f-320e-433a-8c1e-259d241a230e)

This is the error I am getting. It looks like there is no model on the device anymore.

**Comment by rovoe** [comment]
For some reason with the update to v1.0.0-47-ga4ca9913 it lost the default model.
I recreated it with probe_calibrate.

**Comment by RichardTHF** [comment]
Could you post your printer.cfg file please?
