### ISSUE TITLE
BED_MESH_CALIBRATE METHOD=scan crashes latest klipper with `'CartographerProbeWrapper' object has no attribute 'get_status'`

### ISSUE THREAD

**Issue by iMartyn** [Cartographer3D/cartographer-klipper#29]
New install, as of today, cannot help pinpoint what change broke this because I have never had a carto before.

cartographer-klipper version : v1.0.0-50-gf9c27d38 
klipper version : v0.12.0-286-g81de9a86 
![image](https://github.com/user-attachments/assets/bad0e623-1575-4099-a2d5-5d485e627f8f)

G28 worked fine, QUAD_GANTRY_LEVEL works fine.

**Comment by iMartyn** [comment]
So for reference if anyone comes to this issue... don't add a `METHOD=` on cartographer, it's unneeded and crashes.

**Comment by krautech** [comment]
@iMartyn I'll or someone else will look into making sure no extra commands cause this to error out and instead get ignored.

👍🏻

**Comment by iMartyn** [comment]
Yes, so I was looking for recommended settings to put in `[bed_mesh]` because I was moving from klicky to cartographer and my thought process was "well, the point of a bed scanner like cartographer is to have more points, so what should I change, and the FAQ for no bed mesh sent me to [the klipper docs](https://www.klipper3d.org/Bed_Mesh.html) and the [section on bed scanners](https://www.klipper3d.org/Bed_Mesh.html#surface-scans) has the detail on adding `METHOD=`.  Perhaps an example `[bed_mesh]` section on the cartographer docs site might avoid people getting docs from klipper where things are sometimes not accurate for the specifics?

**Comment by krautech** [comment]
Sorry i'm replying to this so late. [bed_mesh] examples have been added to docs :)
