### ISSUE TITLE
[Feature Request] Fuzzy Probing for Nozzle Based Probes

### ISSUE THREAD

**Issue by waffenbesitz** [Cartographer3D/cartographer-klipper#35]
Basic thing add it so u have a Tolerance u can set for what it moves in probing due to constant probing in one spot creates dents.

**Comment by krautech** [comment]
[Added to KrauTech Nightly Branch](https://github.com/Cartographer3D/cartographer-klipper/commit/d503b4743de55d5401157cfb9997692f774bc6c2)
