### ISSUE TITLE
Disabling cartographer mcu during print

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [Cartographer3D/cartographer-klipper#37]
My actual issue is that the Cartorapher probe device is constantly loaded between 35-45% and adding to the heat collected off the heated bed and printed part.

I do realize the cartographer probe is needed only when probing and meshing, and during the print there is no actual use of it.

Is there any way to suspend / disable the probe during actual print, lets say starting with second layer or so? Is it feasible?

![Screenshot_20240928_19:33 57](https://github.com/user-attachments/assets/78cc90f0-2386-40e4-b91e-c699f1bb90e0)
![Screenshot_20240928_19:33 46](https://github.com/user-attachments/assets/1fae2f65-7fe1-436c-9900-7976f2152c0d)

**Comment by Maokaman1** [comment]
Creality K1 FW variant `Survey_Cartographer_K1_USB_8kib_offset.bin` is still v5.0.0. Is this intended?

**Comment by krautech** [comment]
I'll make sure 5.0.2 is added today for K series.

But also, let me just check if the fix for K series isn't just in the normal firmware now
