### ISSUE TITLE
mcu 'scanner': Unable to extract params from: config_lis2dw

### ISSUE THREAD

**Issue by Travis90x** [Cartographer3D/cartographer-klipper#39]
My printer.cfg
IDM scanner flashed with 
~/cartographer-klipper/firmware/v2-v3/survey/Survey_Cartographer_USB_8kib_offset.bin

my bootloader serial 
/dev/serial/by-id/usb-katapult_stm32f042x6_2C0013001743565537353020-if00

[scanner]
serial: /dev/serial/by-id/usb-Cartographer_614e_2C0013001743565537353020-if0
x_offset: 0     
y_offset: 15   
backlash_comp: 0.5
calibration_method: touch
sensor: cartographer
sensor_alt: carto
scanner_touch_z_offset: 0.05  
mesh_runs: 2

[lis2dw]
cs_pin: scanner:PA3
spi_bus: spi1

[resonance_tester]
accel_chip: lis2dw
probe_points: 150, 150, 150 
min_freq: 25
max_freq: 150

[bed_mesh]
zero_reference_position: 175, 175

![immagine](https://github.com/user-attachments/assets/d293c00c-819e-460d-b977-dfa3f3f20d20)

if I disable 
[resonance_tester] and [lis2dw]

![immagine](https://github.com/user-attachments/assets/a0863783-b768-4807-8afe-660d228e84a8)

**Comment by RichardTHF** [comment]
fixed with latest firmware update :)

**Comment by Travis90x** [comment]
> fixed with latest firmware update :)

Thanks for the fix 
![immagine](https://github.com/user-attachments/assets/2d575377-ebef-4b1a-b0d8-05839ff07bd2)
