### ISSUE TITLE
Beta: `MOVE` needs configuration option

### ISSUE THREAD

**Issue by krautech** [Cartographer3D/cartographer-klipper#89]
### Issue Description
`
CARTOGRAPHER_TOUCH` and `CARTOGRAPHER_TOUCH` should have a configuration option in printer.cfg to globally set `MOVE`

Present on: beta only

**Comment by yell3D** [comment]
Tasks:

- [ ] rename `move` to something that makes sense, like `fuzzy_touch`, `fuzzy_radius` or `touch_area_size`
- [ ] add config option (same or closely named) `fuzzy_touch: [0-100]` where `0` would disable the functionality
