### ISSUE TITLE
[Feature] make a `[cartographer]` compatibility layer

### ISSUE THREAD

**Issue by yell3D** [Cartographer3D/cartographer-klipper#98]
* dont error out with command format but continue loading
* map existing `[cartographer]` values to `[scanner]`
* assuming defaults with `calibration_method: scan` 
* print a information Text with a link to the corresponding docs page 
    * on load
    * on `CARTOGRAPHER_CALIBRATE` 
    * on home

**Comment by krautech** [comment]
Which [cartographer] values are you talking about?

**Comment by yell3D** [comment]
closing this after discord discussion.
